# Generated by Django 5.2.4 on 2025-07-22 15:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='음식명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('category', models.CharField(choices=[('menu', 'Menu'), ('drinks', 'Drinks')], max_length=10, verbose_name='카테고리')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('image', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('sold_out', models.BooleanField(default=False, verbose_name='품절 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '음식',
                'verbose_name_plural': '음식들',
                'db_table': 'foods',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='주문 ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='주문일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문들',
                'db_table': 'orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='테이블 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '테이블',
                'verbose_name_plural': '테이블들',
                'db_table': 'tables',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('price', models.PositiveIntegerField(verbose_name='주문 당시 가격')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.foodmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='database.ordermodel')),
            ],
            options={
                'verbose_name': '주문 아이템',
                'verbose_name_plural': '주문 아이템들',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='MinusOrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량(음수)')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('reason', models.CharField(choices=[('sold_out', 'Sold Out'), ('unavailable', 'Unavailable'), ('damaged', 'Damaged')], max_length=20, verbose_name='차감 사유')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.foodmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minus_items', to='database.ordermodel')),
            ],
            options={
                'verbose_name': '차감 주문 아이템',
                'verbose_name_plural': '차감 주문 아이템들',
                'db_table': 'minus_order_items',
            },
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.tablemodel', verbose_name='테이블'),
        ),
    ]
