# Generated by Django 5.2.4 on 2025-07-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='결제자 이름'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('pre_order', 'Pre Order'), ('completed', 'Completed')], default='completed', max_length=20, verbose_name='주문 상태'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.tablemodel', verbose_name='테이블'),
        ),
    ]
