# Generated by Django 5.2.4 on 2025-07-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_ordermodel_payer_name_ordermodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.tablemodel', verbose_name='테이블'),
        ),
    ]
