# Generated by Django 5.2.4 on 2025-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_ordermodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='pre_order_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='선주문 총 금액'),
        ),
    ]
