# Generated by Django 5.2.4 on 2025-07-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_ordermodel_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='테이블 이름'),
        ),
    ]
