# Generated by Django 5.2.4 on 2025-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_tablemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='discord_notified',
            field=models.BooleanField(default=False, verbose_name='Discord 알림 전송 여부'),
        ),
    ]
