# Generated by Django 5.2.4 on 2025-09-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_ordermodel_discord_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='category',
            field=models.CharField(choices=[('main', 'Main'), ('side', 'Side')], max_length=10, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='paymentdepositmodel',
            name='amount',
            field=models.IntegerField(verbose_name='입금 금액'),
        ),
    ]
